http:
  listener:
    host: "localhost"
    port: "8083"
    path: "/(transportType)/(transportCompany)"

  requester:
    host: "localhost"
    port: "8081"
    base_path: "/fastGo"
    routes_path: "/routes"
    schedules_path: "/schedules"