http:
  listener:
    host: "localhost"
    port: "8084"
    path: "/{transportType}/{transportCompany}"
  requester:
    host: "localhost"
    port: "8082"
    base_path: "/travelOnTip"
    routes_path: "/routes"
    schedules_path: "/schedules"